import { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { applySeo, languageFromPath, parsePath, pathFor } from "@/config/seo";
import { GRADUATION_YEAR } from "@/config/clinic";

type Language = "en" | "ar" | "ku";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "services.allTitle": "All our treatments",
    "services.allList": "Tooth extraction|Hollywood smile|Veneers|Teeth cleaning & scaling|Teeth whitening|Dental implants|Crowns|Bridges|Zircon crowns|Ceramic (porcelain) crowns|E-max crowns|Dentures|Orthodontics (braces)|Children's dentistry|Cavity treatment & fillings|Root canal treatment|Dental X-ray|Digital impressions (3D scanner)|Guided implant surgery",
    "faq.q12": "Do you do tooth extraction?",
    "faq.a12": "Yes. When a tooth cannot be saved, the doctor extracts it gently under local anaesthetic and explains how to care for the area afterwards, and what can replace the tooth (an implant, a bridge or a denture).",
    "faq.q13": "Do you make bridges, crowns and dentures?",
    "faq.a13": "Yes. We make crowns and bridges in zircon, ceramic (porcelain) and E-max, and full or partial dentures. The doctor helps you choose the material that suits your teeth and budget.",
    "faq.q14": "Can I get a same-day appointment?",
    "faq.a14": "Yes, same-day visits are available. Call or WhatsApp us and we will find you a time today between 3:00 and 9:00 PM (closed Friday). If you are in pain, tell us so we can fit you in quickly.",
    "faq.q15": "How much does a treatment cost?",
    "faq.a15": "Prices depend on your case, so the doctor examines you first and tells you the exact cost before any treatment starts. Send us a WhatsApp message or book a visit to get your treatment plan.",
    "faq.q16": "Do you do dental cleaning (scaling)?",
    "faq.a16": "Yes. We do professional cleaning and polishing to remove tartar and stains and keep your gums healthy. The doctor also checks your teeth for cavities during the visit.",
    "faq.q17": "Do you do orthodontics (braces)?",
    "faq.a17": "Yes. We straighten crooked or crowded teeth with orthodontic treatment. The doctor examines you and takes an X-ray first, then explains the plan and how long it will take.",
    "faq.q18": "Which languages do you speak?",
    "faq.a18": "We speak Kurdish, Arabic and English, so you can explain your problem in the language you prefer.",
    "hero.sameDay": "Same-day visits available",
    "chat.status": "Online • Same-day visits available",
    "chat.welcome": "Hello! 👋 I'm the clinic's assistant. Ask me about treatments, opening hours, location or booking. Same-day visits are available.",
    "chat.quickSameDay": "Can I come today?",
    "chat.quickPrices": "How much does it cost?",
    "chat.quickLocation": "Where is the clinic?",
    "chat.a.hours": "We are open every day from 3:00 PM to 9:00 PM, except Friday. Same-day visits are available.",
    "chat.a.booking": "Tap \"Book\" to send your request on WhatsApp, or call 0750 781 6500. Same-day visits are available, so you can usually come today.",
    "chat.a.contact": "Call 0750 781 6500 or 0778 166 5000, or message us on WhatsApp at 0750 781 6500.",
    "chat.a.services": "We offer implants, veneers and Hollywood smile, braces, fillings and root canal treatment, zircon, ceramic and E-max crowns, bridges and dentures, extraction, cleaning, whitening, children's dentistry and X-rays. Ask me about any of them.",
    "chat.a.thanks": "You're welcome! 😊 If you need anything else, I'm here.",
    "chat.fallback": "I'm not sure I understood. You can ask me about a treatment, prices, hours, location or booking, or talk to the clinic directly:",
    "chat.more": "Anything else? You can also ask:",
    "chat.action.book": "Book a visit",
    "chat.action.whatsapp": "WhatsApp",
    "chat.action.call": "Call",
    "chat.action.directions": "Directions",
    "faq.q7": "Where can I find a dentist in Duhok?",
    "faq.a7": "Dr. Saleem Andraws Dental Clinic is on Qazi Mohammad Road in Duhok, in the Sherko Nuts building, first floor, opposite Hanasa Pharmacy. We are open every day from 3:00 PM to 9:00 PM except Friday. Use the Get Directions button to open the route in Google Maps.",
    "faq.q8": "Do you offer dental implants?",
    "faq.a8": "Yes. We replace missing teeth with dental implants that look and work like natural teeth. The doctor examines you and takes an X-ray first to check whether an implant suits your case.",
    "faq.q9": "Do you make veneers and Hollywood smiles?",
    "faq.a9": "Yes. We make veneers and complete smile makeovers (Hollywood smile), as well as zircon and E-max crowns. You can see real before-and-after cases in our gallery and on Instagram.",
    "faq.q10": "Do you offer teeth whitening?",
    "faq.a10": "Yes. We offer professional teeth whitening at the clinic. The doctor checks your teeth and gums first so the result is safe and even.",
    "faq.q11": "Do you do root canal treatment and fillings?",
    "faq.a11": "Yes. We do root canal treatment to save damaged teeth, and tooth-coloured fillings for cavities.",
    "gallery.showAll": "Show all photos",
    "gallery.showLess": "Show fewer photos",
    "mobile.call": "Call",
    "mobile.whatsapp": "WhatsApp",
    "mobile.book": "Book",
    "hero.googleRating": "Rating on Google",
    "testimonials.googleReview": "Google review",
    "testimonials.readAll": "Read all our reviews on Google",
    "testimonials.leaveReview": "Leave us a review",
    "contact.openInMaps": "Open in Google Maps",
    "contact.instagram": "Follow us on Instagram",
    "booking.fridayClosed": "The clinic is closed on Fridays. Please choose another day.",
    "instagram.badge": "Instagram",
    "instagram.title1": "Our Cases on",
    "instagram.title2": "Instagram",
    "instagram.description": "See real before-and-after cases from our clinic, updated live from our Instagram page.",
    "instagram.follow": "Follow",
    "nav.instagram": "Instagram",
    // Navbar
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.about": "About",
    "nav.gallery": "Gallery",
    "nav.testimonials": "Testimonials",
    "nav.kids": "Kids' Teeth",
    "nav.infographics": "Infographics",
    "nav.links": "All links",
    "nav.case": "Implant case",
    "nav.treatments": "How it's done",
    "nav.posters": "Learn",
    "nav.contact": "Contact",
    "nav.bookAppointment": "Book Appointment",
    "nav.call": "Call",
    
    // Hero
    "hero.badge": "Dentist & Dental Clinic in Duhok",
    "hero.title1": "Your Smile Is Our",
    "hero.title2": "Priority",
    "hero.description": "Experience exceptional dental care with Dr. Saleem Andraws. Combining advanced techniques with a gentle approach for your perfect smile.",
    "hero.credential1": "M.Sc. Oral Radiology",
    "hero.credential2": "B.D.S. - University of Baghdad",
    "hero.bookBtn": "Book Appointment",
    "hero.callBtn": "Call Now",
    "hero.workingHours": "Working Hours",
    "hero.workingHoursValue": "3 PM - 9 PM (Except Fri)",
    "hero.location": "Location",
    "hero.locationValue": "Duhok - Qazi Mohammad Rd",
    "hero.experience": "Experience",
    "hero.years": "{years} Years",
    "hero.happyPatients": "500+ Happy Patients",
    
    // Services
    "services.badge": "Our Services",
    "services.title1": "Comprehensive Dental",
    "services.title2": "Care",
    "services.description": "We offer a wide range of dental services using the latest technology and techniques to ensure your comfort and satisfaction.",
    "services.teethWhitening": "Teeth Whitening",
    "services.teethWhiteningDesc": "Professional whitening treatments for a brighter, more confident smile.",
    "services.dentalImplants": "Dental Implants",
    "services.dentalImplantsDesc": "Permanent implants that replace missing teeth and look and feel natural.",
    "services.cosmeticDentistry": "Veneers & Hollywood Smile",
    "services.cosmeticDentistryDesc": "Veneers, zircon and E-max crowns, and complete smile makeovers.",
    "services.rootCanal": "Root Canal Treatment",
    "services.rootCanalDesc": "Pain-free root canal therapy to save and restore damaged teeth.",
    "services.orthodontics": "Orthodontics",
    "services.orthodonticsDesc": "Braces and clear aligners to straighten teeth and correct the bite.",
    "services.oralRadiology": "Oral Radiology",
    "services.oralRadiologyDesc": "Advanced digital X-rays and imaging for accurate diagnosis.",
    "services.dentalCleaning": "Fillings & Dental Cleaning",
    "services.dentalCleaningDesc": "Tooth-coloured fillings, scaling and polishing for healthy teeth.",
    "services.pediatricDentistry": "Pediatric Dentistry",
    "services.pediatricDentistryDesc": "Gentle and caring dental treatments for children of all ages.",
    "services.startingFrom": "Starting from",
    
    // About
    "about.badge": "About Dr. Saleem",
    "about.title1": "Expert Dental Care You Can",
    "about.title2": "Trust",
    "about.description1": "Dr. Saleem Andraws (also written Salim Andraws) is a dentist in Duhok. He has been treating patients since graduating from the College of Dentistry, University of Baghdad, in 2007: {years} years of experience. In 2023 he also earned a Master's degree in Oral and Maxillofacial Radiology, which helps him read X-rays precisely and plan each treatment carefully.",
    "about.description2": "At our clinic in Duhok, we combine state-of-the-art technology with a warm, patient-centered approach. Whether you need routine dental care or advanced treatments, we're committed to helping you achieve and maintain a healthy, beautiful smile.",
    "about.oralRadiology": "Oral Radiology",
    "about.univBaghdad": "University of Baghdad",
    "about.happyPatients": "Happy Patients",
    "about.yearsExperience": "Years Experience",
    "about.credTitle": "Qualifications",
    "about.cred.bds": "Bachelor of Dental Surgery (B.D.S.), College of Dentistry, University of Baghdad, 2007",
    "about.cred.msc": "Master's degree (M.Sc.) in Oral and Maxillofacial Radiology, 2023",
    "about.cred.years": "{years} years treating patients",
    "about.cred.syndicate": "Member of the Kurdistan Dentists Syndicate, Duhok Branch",
    "about.cred.languages": "Speaks Kurdish (Badini), Arabic and English",
    "about.photoCaption": "Dr. Saleem Andraws, dentist in Duhok",
    
    // Testimonials
    "testimonials.badge": "Testimonials",
    "testimonials.title1": "What Our Patients",
    "testimonials.title2": "Say",
    "testimonials.description": "Real reviews from our patients on Google.",
    
    // Contact
    "contact.badge": "Contact Us",
    "contact.title1": "Get In",
    "contact.title2": "Touch",
    "contact.description": "Ready to schedule your appointment or have questions? We're here to help you achieve your perfect smile.",
    "contact.callUs": "Call Us",
    "contact.emailUs": "Email Us",
    "contact.phone": "Phone",
    "contact.visitUs": "Visit Us",
    "contact.address": "Qazi Mohammad Road, Duhok - Sherko Nuts Building, 1st Floor - Opposite Hanasa Pharmacy",
    "contact.workingHours": "Working Hours",
    "contact.workingHoursValue": "Daily 3:00 PM - 9:00 PM (Except Friday)",
    "contact.whatsapp": "WhatsApp Us",
    "contact.socialMedia": "Social Media",
    "contact.readyToVisit": "Ready to visit?",
    "contact.bookYourAppointment": "Book Your Appointment",
    "contact.getDirections": "Get Directions",
    
    // Footer
    "footer.description": "Professional dental care in Duhok. M.Sc. Oral Radiology, B.D.S. from University of Baghdad. Committed to providing exceptional care for your smile.",
    "footer.quickLinks": "Quick Links",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved.",
    "footer.openDaily": "Open Daily: 3:00 PM - 9:00 PM (Except Friday)",
    "footer.location": "Location",
    
    // Booking Modal
    "booking.title": "Book Appointment",
    "booking.subtitle": "Schedule your visit with Dr. Saleem",
    "booking.fullName": "Full Name",
    "booking.fullNamePlaceholder": "Enter your full name",
    "booking.phone": "Phone Number",
    "booking.phonePlaceholder": "07XXXXXXXXX",
    "booking.service": "Service Required",
    "booking.selectService": "Select a service",
    "booking.continue": "Continue to Date & Time",
    "booking.preferredDate": "Preferred Date",
    "booking.dateNote": "Note: Clinic is closed on Fridays",
    "booking.preferredTime": "Preferred Time",
    "booking.additionalNotes": "Additional Notes (Optional)",
    "booking.notesPlaceholder": "Any special requirements or concerns...",
    "booking.back": "Back",
    "booking.bookViaWhatsapp": "Book via WhatsApp",
    "booking.generalCheckup": "General Checkup",
    
    // Chatbot
    "chat.title": "Dental Assistant",
    "chat.placeholder": "Type your message...",
    "chat.quickServices": "What services do you offer?",
    "chat.quickHours": "Working hours?",
    "chat.quickBooking": "How to book an appointment?",
    
    // Gallery
    "gallery.badge": "Our Gallery",
    "gallery.title1": "See Our",
    "gallery.title2": "Work",
    "gallery.description": "Explore our modern clinic facilities, treatment results, and educational content.",
    "gallery.filterAll": "All",
    "gallery.filterClinic": "Clinic",
    "gallery.filterResults": "Results",
    "gallery.filterEducational": "Educational",
    "gallery.clinicTag": "Clinic",
    "gallery.resultsTag": "Results",
    "gallery.educationalTag": "Educational",
    "gallery.clinicInterior": "Treatment Room",
    "gallery.clinicInteriorDesc": "Our modern treatment room equipped with the latest dental technology.",
    "gallery.receptionArea": "Reception Area",
    "gallery.receptionAreaDesc": "A comfortable and welcoming space for our patients.",
    "gallery.implantResult": "Dental Implant",
    "gallery.implantResultDesc": "Before and after dental implant procedure showing natural-looking results.",
    "gallery.dentalEquipment": "Advanced Equipment",
    "gallery.dentalEquipmentDesc": "State-of-the-art dental equipment for precise treatments.",
    "gallery.dentalCrowns": "Dental Crowns",
    "gallery.dentalCrownsDesc": "High-quality ceramic crowns for perfect smile restoration.",
    "gallery.frontFilling": "Front Tooth Filling",
    "gallery.frontFillingDesc": "Aesthetic anterior composite restoration with natural appearance.",
    "gallery.amalgamReplacement": "Amalgam Replacement",
    "gallery.amalgamReplacementDesc": "Modern composite filling replacing old amalgam for a natural look.",
    "gallery.smileMakeover": "Complete Smile Makeover",
    "gallery.smileMakeoverDesc": "Full mouth rehabilitation transforming a damaged smile into a beautiful one.",
    "gallery.perfectSmile": "Perfect Smile Result",
    "gallery.perfectSmileDesc": "Natural-looking dental veneers creating a harmonious smile.",
    "gallery.hollywoodSmile": "Hollywood Smile",
    "gallery.hollywoodSmileDesc": "Stunning white smile achieved with premium ceramic veneers.",
    "gallery.zirconEmax": "Zircon & E-max Crowns",
    "gallery.zirconEmaxDesc": "Premium natural smile restoration using Zircon and E-max technology.",
    "gallery.smileTransformation": "Smile Transformation",
    "gallery.smileTransformationDesc": "Dramatic before and after showing the power of cosmetic dentistry.",
    "gallery.veneerCase": "Veneer Case",
    "gallery.veneerCaseDesc": "Beautiful smile enhancement with porcelain veneers.",
    "gallery.fullRestoration": "Full Mouth Restoration",
    "gallery.fullRestorationDesc": "Complete dental rehabilitation for a stunning transformation.",
    "gallery.beforeAfterComparison": "Before & After",
    "gallery.beforeAfterComparisonDesc": "Side-by-side comparison showing remarkable dental transformation.",
    // Educational gallery items
    "gallery.eduGumCleaning": "Gum Cleaning Prevention",
    "gallery.eduGumCleaningDesc": "How regular dental cleaning prevents gum inflammation and disease.",
    "gallery.eduGingivitis": "Understanding Gingivitis",
    "gallery.eduGingivitisDesc": "Learn about healthy gums vs. inflamed gums and how to maintain oral health.",
    "gallery.eduKidsBrushing": "Kids Dental Care",
    "gallery.eduKidsBrushingDesc": "Making brushing fun for children - establishing good habits early.",
    "gallery.eduCheckup": "Regular Checkups",
    "gallery.eduCheckupDesc": "Why regular dental checkups prevent problems before they occur.",
    "gallery.eduPlaque": "Plaque & Bacteria",
    "gallery.eduPlaqueDesc": "Understanding how bacterial plaque causes tooth decay and how to prevent it.",
    "gallery.eduPrevention": "Preventive Care Guide",
    "gallery.eduPreventionDesc": "Comprehensive guide to preventing dental problems and maintaining oral health.",
    "gallery.eduModernCare": "Modern Dental Care",
    "gallery.eduModernCareDesc": "Advanced technology and techniques for better dental treatment outcomes.",
    "gallery.eduHealthyGums": "Healthy Gums Guide",
    "gallery.eduHealthyGumsDesc": "Understanding the signs of healthy vs. unhealthy gums for better oral care.",
    
    // FAQ
    "faq.badge": "FAQ",
    "faq.title1": "Frequently Asked",
    "faq.title2": "Questions",
    "faq.description": "Find answers to common questions about our dental services and clinic.",
    "faq.q1": "What are your working hours?",
    "faq.a1": "Our clinic is open daily from 3:00 PM to 9:00 PM, except Fridays. We recommend booking an appointment in advance to ensure availability.",
    "faq.q2": "Do you accept walk-in patients?",
    "faq.a2": "While we welcome walk-ins when possible, we strongly recommend booking an appointment to minimize your waiting time and ensure you receive the best care.",
    "faq.q3": "What dental services do you offer?",
    "faq.a3": "We offer a comprehensive range of services including teeth whitening, dental implants, cosmetic dentistry, root canal treatment, orthodontics, oral radiology, dental cleaning, and pediatric dentistry.",
    "faq.q4": "Is the clinic equipped with modern technology?",
    "faq.a4": "Yes! Our clinic features state-of-the-art digital X-ray equipment, modern sterilization systems, and the latest dental tools to ensure precise and comfortable treatments.",
    "faq.q5": "How can I book an appointment?",
    "faq.a5": "You can book an appointment through our website's booking form, via WhatsApp, or by calling us directly at 07507816500 or 07781665000. We'll confirm your appointment promptly.",
    "faq.q6": "Do you provide dental care for children?",
    "faq.a6": "Absolutely! Dr. Saleem provides gentle and caring dental treatments for children of all ages, making their dental experience comfortable and stress-free.",
    
    // Appointments
    "appointments.badge": "Recent Appointments",
    "appointments.title1": "Trusted by",
    "appointments.title2": "Our Patients",
    "appointments.description": "Join hundreds of satisfied patients who have booked their appointments through our website.",
    "appointments.confirmed": "Confirmed",
    "appointments.pending": "Pending",
    "appointments.thisMonth": "Appointments This Month",
    "appointments.satisfaction": "Patient Satisfaction",
    "appointments.totalPatients": "Happy Patients",
    "appointments.patient1": "Mohammed A.",
    "appointments.patient2": "Sara K.",
    "appointments.patient3": "Ahmed R.",
    "appointments.patient4": "Layla M.",
    "appointments.patient5": "Omar H.",
    "appointments.patient6": "Fatima S.",

    // Welcome Screen
    "welcome.title": "Welcome to Our Clinic",
    "welcome.subtitle": "Your smile is our passion",
    "welcome.skip": "Skip",
  },
  ar: {
    "services.allTitle": "جميع علاجاتنا",
    "services.allList": "قلع الأسنان|ابتسامة هوليود|فينير|تنظيف الأسنان وإزالة الجير|تبييض الأسنان|زراعة الأسنان|تيجان (كراس)|جسور الأسنان|زركون|سيراميك|إيماكس|طقم أسنان (طخم)|تقويم الأسنان|أسنان الأطفال|علاج التسوس والحشوات|حشو العصب|أشعة الأسنان|الطبعة الرقمية (ماسح ثلاثي الأبعاد)|زراعة موجهة بالدليل الجراحي",
    "faq.q12": "هل تعملون قلع الأسنان؟",
    "faq.a12": "نعم. عندما لا يمكن إنقاذ السن، يقلعه الطبيب بلطف تحت التخدير الموضعي، ويشرح لك طريقة العناية بعد القلع وما يمكن أن يعوض السن (زراعة أو جسر أو طقم).",
    "faq.q13": "هل تعملون الجسور والكراس وطقم الأسنان؟",
    "faq.a13": "نعم. نعمل التيجان (الكراس) والجسور من الزركون والسيراميك والإيماكس، ونعمل طقم الأسنان (الطخم) الكامل والجزئي. يساعدك الطبيب في اختيار المادة المناسبة لأسنانك وميزانيتك.",
    "faq.q14": "هل يمكنني الحصول على موعد في نفس اليوم؟",
    "faq.a14": "نعم، المواعيد في نفس اليوم متاحة. اتصل بنا أو راسلنا على واتساب ونجد لك وقتاً اليوم بين الساعة ٣:٠٠ و٩:٠٠ مساءً (الجمعة عطلة). إذا كنت تشعر بألم أخبرنا حتى نستقبلك بأسرع وقت.",
    "faq.q15": "كم تكلفة العلاج؟",
    "faq.a15": "الأسعار تعتمد على حالتك، لذلك يفحصك الطبيب أولاً ويخبرك بالتكلفة بالضبط قبل بدء أي علاج. راسلنا على واتساب أو احجز زيارة لتحصل على خطة علاجك.",
    "faq.q16": "هل تعملون تنظيف الأسنان؟",
    "faq.a16": "نعم. نعمل تنظيف وتلميع الأسنان الاحترافي لإزالة الجير والتصبغات والحفاظ على صحة اللثة، ويفحص الطبيب أسنانك من التسوس خلال الزيارة.",
    "faq.q17": "هل تعملون تقويم الأسنان؟",
    "faq.a17": "نعم. نعالج الأسنان الملتوية أو المزدحمة بتقويم الأسنان. يفحصك الطبيب ويأخذ صورة أشعة أولاً، ثم يشرح لك الخطة والمدة المتوقعة.",
    "faq.q18": "ما هي اللغات التي تتحدثون بها؟",
    "faq.a18": "نتحدث الكردية والعربية والإنجليزية، فتستطيع أن تشرح مشكلتك باللغة التي تفضلها.",
    "hero.sameDay": "مواعيد في نفس اليوم متاحة",
    "chat.status": "متصل • مواعيد في نفس اليوم",
    "chat.welcome": "مرحباً! 👋 أنا مساعد العيادة. اسألني عن العلاجات أو ساعات العمل أو الموقع أو الحجز. المواعيد في نفس اليوم متاحة.",
    "chat.quickSameDay": "هل أقدر أجي اليوم؟",
    "chat.quickPrices": "كم التكلفة؟",
    "chat.quickLocation": "وين العيادة؟",
    "chat.a.hours": "نستقبلكم يومياً من الساعة ٣:٠٠ حتى ٩:٠٠ مساءً ما عدا الجمعة. المواعيد في نفس اليوم متاحة.",
    "chat.a.booking": "اضغط \"حجز موعد\" لإرسال طلبك على واتساب، أو اتصل على 07507816500. المواعيد في نفس اليوم متاحة، فغالباً تقدر تجي اليوم.",
    "chat.a.contact": "اتصل على 07507816500 أو 07781665000، أو راسلنا على واتساب 07507816500.",
    "chat.a.services": "نقدم زراعة الأسنان، الفينير وابتسامة هوليود، التقويم، الحشوات وحشو العصب، الكراس من الزركون والسيراميك والإيماكس، الجسور وطقم الأسنان، القلع، التنظيف، التبييض، أسنان الأطفال والأشعة. اسألني عن أي واحد منها.",
    "chat.a.thanks": "العفو! 😊 إذا احتجت أي شيء آخر أنا موجود.",
    "chat.fallback": "لم أفهم سؤالك تماماً. اسألني عن علاج أو الأسعار أو ساعات العمل أو الموقع أو الحجز، أو تواصل مع العيادة مباشرة:",
    "chat.more": "هل تحتاج شيئاً آخر؟ يمكنك أيضاً أن تسأل:",
    "chat.action.book": "احجز زيارة",
    "chat.action.whatsapp": "واتساب",
    "chat.action.call": "اتصال",
    "chat.action.directions": "الاتجاهات",
    "faq.q7": "أين أجد طبيب أسنان في دهوك؟",
    "faq.a7": "عيادة الدكتور سليم أندراوس لطب الأسنان في شارع قاضي محمد في دهوك، في بناية جرزات شيركو، الطابق الأول، مقابل صيدلية هناسة. نستقبلكم يومياً من الساعة ٣ إلى ٩ مساءً عدا الجمعة. اضغط على زر الاتجاهات لفتح الطريق في خرائط Google.",
    "faq.q8": "هل تقدمون زراعة الأسنان؟",
    "faq.a8": "نعم. نعوض الأسنان المفقودة بزراعة أسنان تبدو وتعمل مثل الأسنان الطبيعية. يفحصك الطبيب ويأخذ صورة أشعة أولاً للتأكد من أن الزراعة مناسبة لحالتك.",
    "faq.q9": "هل تعملون فينير وابتسامة هوليود؟",
    "faq.a9": "نعم. نعمل الفينير وتجميل الابتسامة الكامل (ابتسامة هوليود)، بالإضافة إلى تيجان (كراس) الزركون والإيماكس. يمكنك مشاهدة حالات حقيقية قبل وبعد في معرض الصور وعلى إنستغرام.",
    "faq.q10": "هل تقدمون تبييض الأسنان؟",
    "faq.a10": "نعم. نقدم تبييض الأسنان الاحترافي في العيادة، بعد أن يفحص الطبيب الأسنان واللثة لضمان نتيجة آمنة ومتساوية.",
    "faq.q11": "هل تعملون حشو العصب والحشوات؟",
    "faq.a11": "نعم. نعالج العصب (حشو العصب) لإنقاذ الأسنان المتضررة، ونعمل حشوات تجميلية بلون الأسنان لعلاج التسوس.",
    "gallery.showAll": "عرض كل الصور",
    "gallery.showLess": "عرض صور أقل",
    "mobile.call": "اتصال",
    "mobile.whatsapp": "واتساب",
    "mobile.book": "حجز موعد",
    "hero.googleRating": "التقييم على Google",
    "testimonials.googleReview": "تقييم على Google",
    "testimonials.readAll": "اقرأ جميع تقييماتنا على Google",
    "testimonials.leaveReview": "اترك لنا تقييماً",
    "contact.openInMaps": "افتح في خرائط Google",
    "contact.instagram": "تابعنا على إنستغرام",
    "booking.fridayClosed": "العيادة مغلقة أيام الجمعة. يرجى اختيار يوم آخر.",
    "instagram.badge": "إنستغرام",
    "instagram.title1": "حالاتنا على",
    "instagram.title2": "إنستغرام",
    "instagram.description": "شاهد حالات حقيقية قبل وبعد العلاج من عيادتنا، محدثة مباشرة من صفحتنا على إنستغرام.",
    "instagram.follow": "تابع",
    "nav.instagram": "إنستغرام",
    // Navbar
    "nav.home": "الرئيسية",
    "nav.services": "الخدمات",
    "nav.about": "عن العيادة",
    "nav.gallery": "المعرض",
    "nav.testimonials": "آراء المرضى",
    "nav.kids": "أسنان الأطفال",
    "nav.infographics": "إنفوجرافيك",
    "nav.links": "كل الروابط",
    "nav.case": "حالة زراعة",
    "nav.treatments": "كيف يتم العلاج",
    "nav.posters": "تعليمي",
    "nav.contact": "اتصل بنا",
    "nav.bookAppointment": "حجز موعد",
    "nav.call": "اتصل",
    
    // Hero
    "hero.badge": "طبيب أسنان وعيادة أسنان في دهوك",
    "hero.title1": "ابتسامتك هي",
    "hero.title2": "أولويتنا",
    "hero.description": "استمتع برعاية أسنان استثنائية مع الدكتور سليم أندراوس. نجمع بين التقنيات المتقدمة والنهج اللطيف لابتسامتك المثالية.",
    "hero.credential1": "ماجستير أشعة الفم",
    "hero.credential2": "بكالوريوس طب الأسنان - جامعة بغداد",
    "hero.bookBtn": "حجز موعد",
    "hero.callBtn": "اتصل الآن",
    "hero.workingHours": "ساعات العمل",
    "hero.workingHoursValue": "٣ - ٩ مساءً (عدا الجمعة)",
    "hero.location": "الموقع",
    "hero.locationValue": "دهوك - شارع قاضي محمد",
    "hero.experience": "الخبرة",
    "hero.years": "{years} سنة",
    "hero.happyPatients": "+٥٠٠ مريض سعيد",
    
    // Services
    "services.badge": "خدماتنا",
    "services.title1": "رعاية أسنان",
    "services.title2": "شاملة",
    "services.description": "نقدم مجموعة واسعة من خدمات طب الأسنان باستخدام أحدث التقنيات لضمان راحتك ورضاك.",
    "services.teethWhitening": "تبييض الأسنان",
    "services.teethWhiteningDesc": "علاجات تبييض احترافية لابتسامة أكثر إشراقاً وثقة.",
    "services.dentalImplants": "زراعة الأسنان",
    "services.dentalImplantsDesc": "زراعة أسنان دائمة لتعويض الأسنان المفقودة بمظهر وإحساس طبيعي.",
    "services.cosmeticDentistry": "فينير وابتسامة هوليود",
    "services.cosmeticDentistryDesc": "فينير (قشور الأسنان)، تيجان (كراس) زركون وإيماكس، وتصميم الابتسامة.",
    "services.rootCanal": "علاج العصب (حشو العصب)",
    "services.rootCanalDesc": "علاج وحشو عصب السن بدون ألم لإنقاذ الأسنان المتضررة.",
    "services.orthodontics": "تقويم الأسنان",
    "services.orthodonticsDesc": "تقويم الأسنان الثابت والشفاف لأسنان مستقيمة وإطباق صحيح.",
    "services.oralRadiology": "أشعة الفم",
    "services.oralRadiologyDesc": "أشعة سينية رقمية متقدمة للتشخيص الدقيق.",
    "services.dentalCleaning": "حشو الأسنان وتنظيفها",
    "services.dentalCleaningDesc": "حشوات تجميلية بلون الأسنان، وتنظيف وتلميع احترافي.",
    "services.pediatricDentistry": "طب أسنان الأطفال",
    "services.pediatricDentistryDesc": "علاجات لطيفة للأطفال من جميع الأعمار.",
    "services.startingFrom": "يبدأ من",
    
    // About
    "about.badge": "عن الدكتور سليم",
    "about.title1": "رعاية أسنان خبيرة يمكنك",
    "about.title2": "الوثوق بها",
    "about.description1": "الدكتور سليم أندراوس طبيب أسنان في دهوك، تخرج من كلية طب الأسنان في جامعة بغداد عام ٢٠٠٧، أي {years} عاماً من الخبرة في علاج المرضى. وفي عام ٢٠٢٣ حصل على الماجستير في أشعة الفم والأسنان، مما يساعده على قراءة الأشعة بدقة وتخطيط كل علاج بعناية.",
    "about.description2": "في عيادتنا في دهوك، نجمع بين أحدث التقنيات والنهج الدافئ المتمحور حول المريض. سواء كنت بحاجة إلى رعاية روتينية أو علاجات متقدمة، نحن ملتزمون بمساعدتك.",
    "about.oralRadiology": "أشعة الفم",
    "about.univBaghdad": "جامعة بغداد",
    "about.happyPatients": "مريض سعيد",
    "about.yearsExperience": "سنوات خبرة",
    "about.credTitle": "المؤهلات",
    "about.cred.bds": "بكالوريوس طب وجراحة الفم والأسنان (⁦B.D.S.⁩)، كلية طب الأسنان، جامعة بغداد، ٢٠٠٧",
    "about.cred.msc": "ماجستير (⁦M.Sc.⁩) في أشعة الفم والأسنان، ٢٠٢٣",
    "about.cred.years": "{years} عاماً في علاج المرضى",
    "about.cred.syndicate": "عضو نقابة أطباء أسنان كوردستان، فرع دهوك",
    "about.cred.languages": "يتحدث الكردية (البادينية) والعربية والإنجليزية",
    "about.photoCaption": "الدكتور سليم أندراوس، طبيب أسنان في دهوك",
    
    // Testimonials
    "testimonials.badge": "آراء المرضى",
    "testimonials.title1": "ماذا يقول",
    "testimonials.title2": "مرضانا",
    "testimonials.description": "تقييمات حقيقية من مرضانا على Google.",
    
    // Contact
    "contact.badge": "اتصل بنا",
    "contact.title1": "تواصل",
    "contact.title2": "معنا",
    "contact.description": "هل أنت مستعد لحجز موعدك أو لديك أسئلة؟ نحن هنا لمساعدتك في الحصول على ابتسامتك المثالية.",
    "contact.callUs": "اتصل بنا",
    "contact.emailUs": "راسلنا",
    "contact.phone": "الهاتف",
    "contact.visitUs": "زورنا",
    "contact.address": "دهوك - شارع قاضي محمد - بناية جرزات شيركو، الطابق الأول - مقابل صيدلية هناسة",
    "contact.workingHours": "ساعات العمل",
    "contact.workingHoursValue": "يومياً ٣:٠٠ - ٩:٠٠ مساءً (عدا الجمعة)",
    "contact.whatsapp": "واتساب",
    "contact.socialMedia": "وسائل التواصل",
    "contact.readyToVisit": "مستعد للزيارة؟",
    "contact.bookYourAppointment": "احجز موعدك",
    "contact.getDirections": "احصل على الاتجاهات",
    
    // Footer
    "footer.description": "رعاية أسنان احترافية في دهوك. ماجستير أشعة الفم، بكالوريوس من جامعة بغداد. ملتزمون بتقديم رعاية استثنائية لابتسامتك.",
    "footer.quickLinks": "روابط سريعة",
    "footer.contact": "اتصل بنا",
    "footer.rights": "جميع الحقوق محفوظة.",
    "footer.openDaily": "مفتوح يومياً: ٣:٠٠ - ٩:٠٠ مساءً (عدا الجمعة)",
    "footer.location": "الموقع",
    
    // Booking Modal
    "booking.title": "حجز موعد",
    "booking.subtitle": "حدد موعد زيارتك مع الدكتور سليم",
    "booking.fullName": "الاسم الكامل",
    "booking.fullNamePlaceholder": "أدخل اسمك الكامل",
    "booking.phone": "رقم الهاتف",
    "booking.phonePlaceholder": "07XXXXXXXXX",
    "booking.service": "الخدمة المطلوبة",
    "booking.selectService": "اختر خدمة",
    "booking.continue": "المتابعة لاختيار الوقت",
    "booking.preferredDate": "التاريخ المفضل",
    "booking.dateNote": "ملاحظة: العيادة مغلقة أيام الجمعة",
    "booking.preferredTime": "الوقت المفضل",
    "booking.additionalNotes": "ملاحظات إضافية (اختياري)",
    "booking.notesPlaceholder": "أي متطلبات أو مخاوف خاصة...",
    "booking.back": "رجوع",
    "booking.bookViaWhatsapp": "حجز عبر واتساب",
    "booking.generalCheckup": "فحص عام",
    
    // Chatbot
    "chat.title": "مساعد الأسنان",
    "chat.placeholder": "اكتب رسالتك...",
    "chat.quickServices": "ما هي الخدمات المتوفرة؟",
    "chat.quickHours": "ساعات العمل؟",
    "chat.quickBooking": "كيف أحجز موعد؟",
    
    // Appointments
    "appointments.badge": "المواعيد الأخيرة",
    "appointments.title1": "موثوق من قبل",
    "appointments.title2": "مرضانا",
    "appointments.description": "انضم إلى مئات المرضى الراضين الذين حجزوا مواعيدهم عبر موقعنا.",
    "appointments.confirmed": "مؤكد",
    "appointments.pending": "قيد الانتظار",
    "appointments.thisMonth": "مواعيد هذا الشهر",
    "appointments.satisfaction": "رضا المرضى",
    "appointments.totalPatients": "مرضى سعداء",
    "appointments.patient1": "محمد أ.",
    "appointments.patient2": "سارة ك.",
    "appointments.patient3": "أحمد ر.",
    "appointments.patient4": "ليلى م.",
    "appointments.patient5": "عمر ح.",
    "appointments.patient6": "فاطمة س.",
    
    // Gallery
    "gallery.badge": "معرض الصور",
    "gallery.title1": "شاهد",
    "gallery.title2": "أعمالنا",
    "gallery.description": "استكشف مرافق عيادتنا الحديثة ونتائج العلاج والمحتوى التعليمي.",
    "gallery.filterAll": "الكل",
    "gallery.filterClinic": "العيادة",
    "gallery.filterResults": "النتائج",
    "gallery.filterEducational": "تعليمي",
    "gallery.clinicTag": "العيادة",
    "gallery.resultsTag": "النتائج",
    "gallery.educationalTag": "تعليمي",
    "gallery.clinicInterior": "غرفة العلاج",
    "gallery.clinicInteriorDesc": "غرفة العلاج الحديثة مجهزة بأحدث تقنيات طب الأسنان.",
    "gallery.receptionArea": "منطقة الاستقبال",
    "gallery.receptionAreaDesc": "مساحة مريحة ومرحبة لمرضانا.",
    "gallery.implantResult": "زراعة الأسنان",
    "gallery.implantResultDesc": "قبل وبعد إجراء زراعة الأسنان بنتائج طبيعية.",
    "gallery.dentalEquipment": "معدات متقدمة",
    "gallery.dentalEquipmentDesc": "معدات طب أسنان حديثة للعلاجات الدقيقة.",
    "gallery.dentalCrowns": "تيجان الأسنان",
    "gallery.dentalCrownsDesc": "تيجان سيراميك عالية الجودة لاستعادة الابتسامة المثالية.",
    // New gallery items
    "gallery.frontFilling": "حشوة الأسنان الأمامية",
    "gallery.frontFillingDesc": "ترميم تجميلي للأسنان الأمامية بمظهر طبيعي.",
    "gallery.amalgamReplacement": "استبدال حشوة الأملغم",
    "gallery.amalgamReplacementDesc": "حشوة حديثة تستبدل الأملغم القديم بمظهر طبيعي.",
    "gallery.smileMakeover": "تجميل الابتسامة الكاملة",
    "gallery.smileMakeoverDesc": "إعادة تأهيل كامل للفم تحوّل الابتسامة التالفة إلى ابتسامة جميلة.",
    "gallery.perfectSmile": "نتيجة ابتسامة مثالية",
    "gallery.perfectSmileDesc": "قشور أسنان طبيعية المظهر تخلق ابتسامة متناغمة.",
    "gallery.hollywoodSmile": "ابتسامة هوليوود",
    "gallery.hollywoodSmileDesc": "ابتسامة بيضاء مذهلة تحققت بقشور السيراميك الفاخرة.",
    "gallery.zirconEmax": "تيجان زيركون وإيماكس",
    "gallery.zirconEmaxDesc": "ترميم ابتسامة طبيعية فاخرة باستخدام تقنية الزيركون والإيماكس.",
    "gallery.smileTransformation": "تحويل الابتسامة",
    "gallery.smileTransformationDesc": "قبل وبعد مذهل يظهر قوة طب الأسنان التجميلي.",
    "gallery.veneerCase": "حالة قشور الأسنان",
    "gallery.veneerCaseDesc": "تحسين جميل للابتسامة بقشور البورسلين.",
    "gallery.fullRestoration": "ترميم كامل للفم",
    "gallery.fullRestorationDesc": "إعادة تأهيل شاملة للأسنان بتحول مذهل.",
    "gallery.beforeAfterComparison": "قبل وبعد",
    "gallery.beforeAfterComparisonDesc": "مقارنة جنباً إلى جنب تظهر تحولاً مذهلاً للأسنان.",
    // Educational gallery items
    "gallery.eduGumCleaning": "الوقاية من التهاب اللثة",
    "gallery.eduGumCleaningDesc": "كيف يمنع تنظيف الأسنان المنتظم التهاب اللثة.",
    "gallery.eduGingivitis": "فهم التهاب اللثة",
    "gallery.eduGingivitisDesc": "تعرف على اللثة الصحية مقابل الملتهبة.",
    "gallery.eduKidsBrushing": "رعاية أسنان الأطفال",
    "gallery.eduKidsBrushingDesc": "اجعل تنظيف الأسنان ممتعاً للأطفال.",
    "gallery.eduCheckup": "الفحوصات الدورية",
    "gallery.eduCheckupDesc": "لماذا الفحوصات المنتظمة تمنع المشاكل قبل حدوثها.",
    "gallery.eduPlaque": "البلاك والبكتيريا",
    "gallery.eduPlaqueDesc": "فهم كيف يسبب البلاك تسوس الأسنان.",
    "gallery.eduPrevention": "دليل الوقاية",
    "gallery.eduPreventionDesc": "دليل شامل للوقاية من مشاكل الأسنان.",
    "gallery.eduModernCare": "رعاية الأسنان الحديثة",
    "gallery.eduModernCareDesc": "تقنيات متقدمة لنتائج أفضل.",
    "gallery.eduHealthyGums": "دليل اللثة الصحية",
    "gallery.eduHealthyGumsDesc": "فهم علامات اللثة الصحية مقابل غير الصحية.",
    
    // FAQ
    "faq.badge": "الأسئلة الشائعة",
    "faq.title1": "الأسئلة",
    "faq.title2": "الشائعة",
    "faq.description": "اعثر على إجابات للأسئلة الشائعة حول خدماتنا وعيادتنا.",
    "faq.q1": "ما هي ساعات العمل؟",
    "faq.a1": "عيادتنا مفتوحة يومياً من الساعة ٣:٠٠ مساءً حتى ٩:٠٠ مساءً، ما عدا أيام الجمعة. ننصح بحجز موعد مسبقاً لضمان التوفر.",
    "faq.q2": "هل تقبلون المرضى بدون موعد؟",
    "faq.a2": "نرحب بالمرضى بدون موعد عند الإمكان، لكن ننصح بشدة بحجز موعد لتقليل وقت الانتظار وضمان أفضل رعاية.",
    "faq.q3": "ما هي خدمات الأسنان التي تقدمونها؟",
    "faq.a3": "نقدم مجموعة شاملة من الخدمات تشمل تبييض الأسنان، زراعة الأسنان، طب الأسنان التجميلي، علاج قناة الجذر، تقويم الأسنان، أشعة الفم، تنظيف الأسنان، وطب أسنان الأطفال.",
    "faq.q4": "هل العيادة مجهزة بتقنيات حديثة؟",
    "faq.a4": "نعم! تتميز عيادتنا بأحدث أجهزة الأشعة السينية الرقمية وأنظمة التعقيم الحديثة وأحدث أدوات طب الأسنان لضمان علاجات دقيقة ومريحة.",
    "faq.q5": "كيف يمكنني حجز موعد؟",
    "faq.a5": "يمكنك حجز موعد من خلال نموذج الحجز على موقعنا، عبر واتساب، أو بالاتصال بنا مباشرة على 07507816500 أو 07781665000. سنؤكد موعدك على الفور.",
    "faq.q6": "هل تقدمون رعاية أسنان للأطفال؟",
    "faq.a6": "بالتأكيد! يقدم الدكتور سليم علاجات أسنان لطيفة ومحبة للأطفال من جميع الأعمار، مما يجعل تجربتهم مريحة وخالية من التوتر.",

    // Welcome Screen
    "welcome.title": "مرحباً بكم في عيادتنا",
    "welcome.subtitle": "ابتسامتك هي شغفنا",
    "welcome.skip": "تخطي",
  },
  ku: {
    "services.allTitle": "هەمی چارەسەریێن مە",
    "services.allList": "هەلکێشانا ددانا (هلكيشان، قلع)|بزەیا هۆلیوود (هوليود سمايل)|ڤینیر|پاقژکرنا ددانا (تنظيف)|سپیکرنا ددانا (تبييض)|چاندنا ددانا (جاندن)|کراس|جسر|زیرکۆن|سیرامیک|ئیماکس|تەخمێ ددانا (طخم)|تقویم|ددانێن زارۆکان|چارەسەریا کڕمبوونێ (تسوس)|حەشوا دەمارێ|تیشکا ددانا|قالبێ دیجیتالی (سکانەرا ٣D)|چاندنا ب ڕێبەرێ نەشتەرگەری",
    "faq.q12": "ئەرێ هوین ددانا هەلدکێشن (قلع)؟",
    "faq.a12": "بەلێ. دەمێ ددان نەهێتە ڕزگارکرن، دکتۆر ب نەرمی و ب سڕکرنا جهی هەلدکێشیت، و بۆ تە دبێژیت پشتی هەلکێشانێ چاوا خۆ بپارێزی و چ دشێت جهێ ددانی بگریت (چاندن، جسر یان تەخم).",
    "faq.q13": "ئەرێ هوین جسر، کراس و تەخمێ ددانا دکەن؟",
    "faq.a13": "بەلێ. کراس و جسران ژ زیرکۆن، سیرامیک و ئیماکس دکەین، و تەخمێ ددانا (طخم) یێ تەمام و یێ پشکی. دکتۆر هاریکاریا تە دکەت ماددێ گونجای بۆ ددانێن تە و بودجەیا تە هەلبژێری.",
    "faq.q14": "ئەرێ دشێم هەمان ڕۆژ نۆرەیێ وەربگرم؟",
    "faq.a14": "بەلێ، سەردان د هەمان ڕۆژێ دا بەردەستە. پەیوەندیێ ب مە بکە یان ل واتساپێ نامەیەکێ بفرێکە و ئەم ئەڤرۆ دەمەکێ بۆ تە دبینین، د ناڤبەرا ٣:٠٠ و ٩:٠٠ ئێڤاری دا (ئینی گرتییە). ئەگەر ئێشا تە هەبیت بێژە مە دا زوو تە ببینین.",
    "faq.q15": "بهایێ چارەسەریێ چەندە؟",
    "faq.a15": "بها ل دویڤ حالەتێ تە یە، لەوما دکتۆر پێشی تە دپشکنیت و بهایێ دروست بەری دەستپێکرنا چارەسەریێ بۆ تە دبێژیت. ل واتساپێ نامەیەکێ بفرێکە یان نۆرەیەکێ بگرە.",
    "faq.q16": "ئەرێ هوین ددانا پاقژ دکەن (تنظیف)؟",
    "faq.a16": "بەلێ. پاقژکرن و بریقەدانا ددانا یا پیشەیی دکەین دا کلس و ڕەنگ بچن و پوک ساخلەم بمینن. دکتۆر د سەردانێ دا ددانێن تە ژ کڕمبوونێ ژی دپشکنیت.",
    "faq.q17": "ئەرێ هوین ڕێکخستنا ددانا (تقویم) دکەن؟",
    "faq.a17": "بەلێ. ددانێن خوار یان تێکەل ب تقویمێ ڕێک دئێخین. دکتۆر پێشی تە دپشکنیت و تیشکێ دگریت، پاشی پلان و دەمێ پێدڤی بۆ تە ڕوون دکەت.",
    "faq.q18": "هوین ب چ زمانان دئاخڤن؟",
    "faq.a18": "ئەم ب کوردی، عەرەبی و ئینگلیزی دئاخڤین، لەوما دشێی ب وی زمانێ تو حەز دکەی کێشا خۆ بێژی.",
    "hero.sameDay": "سەردان د هەمان ڕۆژێ دا بەردەستە",
    "chat.status": "سەرهێڵ • سەردان د هەمان ڕۆژێ دا",
    "chat.welcome": "سڵاو! 👋 ئەز هاریکارێ کلینیکێ مە. پسیارێ ل سەر چارەسەری، دەمێن کاری، جهێ کلینیکێ یان نۆرەگرتنێ بکە. سەردان د هەمان ڕۆژێ دا بەردەستە.",
    "chat.quickSameDay": "دشێم ئەڤرۆ بێم؟",
    "chat.quickPrices": "بها چەندە؟",
    "chat.quickLocation": "کلینیک ل کیرێ یە؟",
    "chat.a.hours": "هەمی ڕۆژان ژ دەمژمێر ٣:٠٠ هەتا ٩:٠٠ ئێڤاری ڤەکری یە، ژبلی ئینیێ. سەردان د هەمان ڕۆژێ دا بەردەستە.",
    "chat.a.booking": "کلیک ل سەر \"نۆرە\" بکە دا داخوازا تە ب واتساپێ بچیت، یان پەیوەندیێ ب 07507816500 بکە. سەردان د هەمان ڕۆژێ دا بەردەستە.",
    "chat.a.contact": "پەیوەندیێ ب 07507816500 یان 07781665000 بکە، یان ل واتساپێ 07507816500 نامەیەکێ بفرێکە.",
    "chat.a.services": "چاندنا ددانا، ڤینیر و بزەیا هۆلیوود، تقویم، حەشو و حەشوا دەمارێ، کراسێن زیرکۆن، سیرامیک و ئیماکس، جسر و تەخمێ ددانا، هەلکێشان، پاقژکرن، سپیکرن، ددانێن زارۆکان و تیشک. پسیارێ ل سەر هەر ئێکێ بکە.",
    "chat.a.thanks": "سوپاس بۆ تە! 😊 ئەگەر تشتەکێ دی پێدڤی بیت ئەز ل ڤێرێ مە.",
    "chat.fallback": "باش تێنەگەهشتم. پسیارێ ل سەر چارەسەریەکێ، بها، دەمێن کاری، جهـ یان نۆرەگرتنێ بکە، یان ڕاستەوخۆ ب کلینیکێ ڕە باخڤە:",
    "chat.more": "تشتەکێ دی؟ دشێی ڤان ژی بپرسی:",
    "chat.action.book": "نۆرە بگرە",
    "chat.action.whatsapp": "واتساپ",
    "chat.action.call": "پەیوەندی",
    "chat.action.directions": "ڕێنیشاندان",
    "faq.q7": "ل دهوکێ دکتورێ ددانا ل کیرێ یە؟",
    "faq.a7": "کلینیکا ددانا یا دکتۆر سەلیم ئەندراوس ل شەقامێ قازی محەمەد ل دهوکێ یە، ل ئاڤاهیێ جرزاتی شیرکۆ، قاتێ ئێکێ، بەرامبەر دەرمانخانەی هانەسە. هەموو ڕۆژێ ژ دەمژمێر ٣ تا ٩ێ ئێڤاری ڤەکری یە، ژ بلی ئینیێ. دوگمەیا ئاراستەکان بکە دا ڕێ ل نەخشەیا Google ڤەبیت.",
    "faq.q8": "ئەرێ هوین چاندنا ددانا دکەن؟",
    "faq.a8": "بەلێ. ددانێن کەفتی ب چاندنا ددانا دگوهۆڕین کو وەک ددانێن سروشتی دیار دبن و کار دکەن. دکتۆر پێشی تە دپشکنیت و تیشکێ دگریت دا بزانیت چاندن بۆ تە گونجایە.",
    "faq.q9": "ئەرێ هوین ڤینیر و بزەیا هۆلیوود دکەن؟",
    "faq.a9": "بەلێ. ڤینیر و جوانکرنا تەواوی یا بزەیێ (بزەیا هۆلیوود) دکەین، هەروەسا کراسێن زیرکۆن و ئیماکس. دشێی نموونەیێن ڕاستەقینە یێن بەری و پشتی ل گەلەریێ و ل ئینستاگرامێ ببینی.",
    "faq.q10": "ئەرێ هوین سپیکرنا ددانا دکەن؟",
    "faq.a10": "بەلێ. سپیکرنا ددانا یا پیشەیی ل کلینیکێ دکەین، پشتی دکتۆر ددان و پوکێن تە دپشکنیت دا ئەنجام سەلامەت و یەکسان بیت.",
    "faq.q11": "ئەرێ هوین حەشوا دەمارێ و حەشوا ددانا دکەن؟",
    "faq.a11": "بەلێ. چارەسەریا دەمارێ (حەشوا دەمارێ) دکەین دا ددانێن زیانلێکەفتی ڕزگار بکەین، و حەشوێن ب ڕەنگێ ددانی بۆ کڕمبوونێ.",
    "gallery.showAll": "هەموو وێنەکان ببینە",
    "gallery.showLess": "وێنەی کەمتر",
    "mobile.call": "پەیوەندی",
    "mobile.whatsapp": "واتساپ",
    "mobile.book": "نۆرە",
    "hero.googleRating": "هەڵسەنگاندن لە Google",
    "testimonials.googleReview": "بۆچوون لە Google",
    "testimonials.readAll": "هەموو بۆچوونەکانمان لە Google بخوێنەوە",
    "testimonials.leaveReview": "بۆچوونێکمان بۆ بنووسە",
    "contact.openInMaps": "لە نەخشەی Google بیکەرەوە",
    "contact.instagram": "لە ئینستاگرام فۆڵۆومان بکە",
    "booking.fridayClosed": "کلینیک ڕۆژی هەینی داخراوە. تکایە ڕۆژێکی تر هەڵبژێرە.",
    "instagram.badge": "ئینستاگرام",
    "instagram.title1": "کەیسەکانمان لە",
    "instagram.title2": "ئینستاگرام",
    "instagram.description": "کەیسی ڕاستەقینەی پێش و دوای چارەسەر لە کلینیکەکەمان ببینە، ڕاستەوخۆ لە پەڕەی ئینستاگرامەکەمانەوە.",
    "instagram.follow": "فۆڵۆومان بکە",
    "nav.instagram": "ئینستاگرام",
    // Navbar
    "nav.home": "سەرەتا",
    "nav.services": "خزمەتگوزارییەکان",
    "nav.about": "دەربارە",
    "nav.gallery": "گەلەری",
    "nav.testimonials": "بۆچوونەکان",
    "nav.kids": "ددانێن زارۆکان",
    "nav.infographics": "ئینفۆگرافیک",
    "nav.links": "هەمی لینک",
    "nav.case": "حالەتا چاندنێ",
    "nav.treatments": "چاوا دئێتە کرن",
    "nav.posters": "فێرکاری",
    "nav.contact": "پەیوەندی",
    "nav.bookAppointment": "نۆرەی پزیشک",
    "nav.call": "پەیوەندی",
    
    // Hero
    "hero.badge": "دکتۆرێ ددانا و کلینیکا ددانا ل دهۆک",
    "hero.title1": "بزەیی تۆ",
    "hero.title2": "گرنگە بۆمان",
    "hero.description": "چاودێری ددانی نایاب لەگەڵ دکتۆر سەلیم ئەندراوس. تەکنیکی پێشکەوتوو لەگەڵ ڕێبازێکی نەرم بۆ بزەیی تەواوت.",
    "hero.credential1": "ماستەر لە تیشکی دەم",
    "hero.credential2": "بەکالۆریۆس - زانکۆی بەغدا",
    "hero.bookBtn": "نۆرەی پزیشک",
    "hero.callBtn": "پەیوەندی بکە",
    "hero.workingHours": "کاتی کارکردن",
    "hero.workingHoursValue": "٣ - ٩ ئێوارە (جگە لە هەینی)",
    "hero.location": "شوێن",
    "hero.locationValue": "دهۆک - شەقامی قازی محەمەد",
    "hero.experience": "ئەزموون",
    "hero.years": "{years} ساڵ",
    "hero.happyPatients": "+٥٠٠ نەخۆشی دڵخۆش",
    
    // Services
    "services.badge": "خزمەتگوزارییەکانمان",
    "services.title1": "چاودێری ددانی",
    "services.title2": "تەواو",
    "services.description": "کۆمەڵێک خزمەتگوزاری ددان بە بەکارهێنانی تەکنەلۆژیای هەرە نوێ پێشکەش دەکەین بۆ ئارامی و ڕازیبوونت.",
    "services.teethWhitening": "سپیکردنەوەی ددان",
    "services.teethWhiteningDesc": "چارەسەری سپیکردنەوەی پیشەگەری بۆ بزەیەکی درەوشاوەتر.",
    "services.dentalImplants": "چاندنی ددان",
    "services.dentalImplantsDesc": "چارەسەری دانانەوەی ددانی هەمیشەیی بە شێوەیەکی سروشتی.",
    "services.cosmeticDentistry": "ڤینیر و بزەی هۆلیوود",
    "services.cosmeticDentistryDesc": "ڤینیر، کراسی زیرکۆن و ئیماکس، و دیزاینی تەواوی بزە.",
    "services.rootCanal": "چارەسەری دەمار (حەشوی دەمار)",
    "services.rootCanalDesc": "چارەسەری و حەشوی دەماری ددان بێ ئازار بۆ ڕزگارکردنی ددان.",
    "services.orthodontics": "ڕێکخستنی ددان (تقویم)",
    "services.orthodonticsDesc": "برەیسیس و ئەلایننەر بۆ ڕیزکردنی تەواوی ددان.",
    "services.oralRadiology": "تیشکی دەم",
    "services.oralRadiologyDesc": "تیشکی ئێکسی دیجیتاڵی پێشکەوتوو بۆ دەستنیشانکردنی وردی نەخۆشی.",
    "services.dentalCleaning": "حەشو و پاککردنەوەی ددان",
    "services.dentalCleaningDesc": "حەشوی ڕەنگی ددان، پاککردنەوە و بریقاندن بۆ ددانی تەندروست.",
    "services.pediatricDentistry": "ددانی منداڵان",
    "services.pediatricDentistryDesc": "چارەسەری نەرم بۆ منداڵانی هەموو تەمەنێک.",
    "services.startingFrom": "دەست پێدەکات لە",
    
    // About
    "about.badge": "دەربارەی دکتۆر سەلیم",
    "about.title1": "چاودێری ددانی شارەزا کە دەتوانیت",
    "about.title2": "متمانەی پێبکەیت",
    "about.description1": "دکتۆر سەلیم ئەندراوس نوژدارێ ددانا یە ل دهوکێ. ساڵا ٢٠٠٧ ژ کۆلیژا نوژداریا ددانا ل زانکۆیا بەغدا دەرچوویە، ئانکو {years} ساڵ ئەزموون د چارەسەریا نەخۆشان دا. ساڵا ٢٠٢٣ ماستەر ل تیشکا دەم و ددانا وەرگرت، کو هاریکاریا وی دکەت تیشکان ب دروستی بخوینیت و هەر چارەسەریەکێ ب هویری پلان بکەت.",
    "about.description2": "لە کلینیکەکەماندا لە دهۆک، تەکنەلۆژیای پێشکەوتوو دەگەڵ ڕێبازێکی گەرم و نەخۆش-ناوەندی تێکەڵ دەکەین.",
    "about.oralRadiology": "تیشکی دەم",
    "about.univBaghdad": "زانکۆی بەغدا",
    "about.happyPatients": "نەخۆشی دڵخۆش",
    "about.yearsExperience": "ساڵ ئەزموون",
    "about.credTitle": "بڕوانامە",
    "about.cred.bds": "بەکالۆریۆس ل نوژداریا ددانا (⁦B.D.S.⁩)، کۆلیژا نوژداریا ددانا، زانکۆیا بەغدا، ٢٠٠٧",
    "about.cred.msc": "ماستەر (⁦M.Sc.⁩) ل تیشکا دەم و ددانا، ٢٠٢٣",
    "about.cred.years": "{years} ساڵ چارەسەریا نەخۆشان",
    "about.cred.syndicate": "ئەندامێ سەندیکایا نوژدارێن ددانا یا کوردستانێ، لقێ دهوکێ",
    "about.cred.languages": "ب کوردی (بادینی)، عەرەبی و ئینگلیزی دئاخڤیت",
    "about.photoCaption": "دکتۆر سەلیم ئەندراوس، نوژدارێ ددانا ل دهوکێ",
    
    // Testimonials
    "testimonials.badge": "بۆچوونەکان",
    "testimonials.title1": "نەخۆشەکانمان چی",
    "testimonials.title2": "دەڵێن",
    "testimonials.description": "بۆچوونی ڕاستەقینەی نەخۆشەکانمان لە Google.",
    
    // Contact
    "contact.badge": "پەیوەندیمان پێوە بکە",
    "contact.title1": "پەیوەندی",
    "contact.title2": "بکە",
    "contact.description": "ئامادەیت بۆ دانانی نۆرەی پزیشک یان پرسیارت هەیە؟ ئێمە لێرەین بۆ یارمەتیت بۆ بەدەستهێنانی بزەیی تەواوت.",
    "contact.callUs": "پەیوەندیمان پێوە بکە",
    "contact.emailUs": "ئیمەیڵمان بۆ بنێرە",
    "contact.phone": "تەلەفۆن",
    "contact.visitUs": "سەردانمان بکە",
    "contact.address": "دهۆک - شەقامی قازی محەمەد - ئاڤاهیێ جرزاتی شیرکۆ، قاتێ ئێکێ - بەرامبەر دەرمانخانەی هانەسە",
    "contact.workingHours": "کاتی کارکردن",
    "contact.workingHoursValue": "ڕۆژانە ٣:٠٠ - ٩:٠٠ ئێوارە (جگە لە هەینی)",
    "contact.whatsapp": "واتساپ",
    "contact.socialMedia": "تۆڕە کۆمەڵایەتییەکان",
    "contact.readyToVisit": "ئامادەیت بۆ سەردان؟",
    "contact.bookYourAppointment": "نۆرەی پزیشکت دابنێ",
    "contact.getDirections": "ئاراستەکان بەدەستبهێنە",
    
    // Footer
    "footer.description": "چاودێری ددانی پیشەگەری لە دهۆک. ماستەر تیشکی دەم، بەکالۆریۆس لە زانکۆی بەغدا. پابەندین بە پێشکەشکردنی چاودێری نایاب بۆ بزەیت.",
    "footer.quickLinks": "لینکە خێراکان",
    "footer.contact": "پەیوەندی",
    "footer.rights": "هەموو مافەکان پارێزراون.",
    "footer.openDaily": "کراوەیە ڕۆژانە: ٣:٠٠ - ٩:٠٠ ئێوارە (جگە لە هەینی)",
    
    // Booking Modal
    "booking.title": "نۆرەی پزیشک",
    "booking.subtitle": "سەردانت بۆ دکتۆر سەلیم دابنێ",
    "booking.fullName": "ناوی تەواو",
    "booking.fullNamePlaceholder": "ناوی تەواوت بنووسە",
    "booking.phone": "ژمارەی تەلەفۆن",
    "booking.phonePlaceholder": "07XXXXXXXXX",
    "booking.service": "خزمەتگوزاری پێویست",
    "booking.selectService": "خزمەتگوزارییەک هەڵبژێرە",
    "booking.continue": "بەردەوامبوون بۆ کات و ڕۆژ",
    "booking.preferredDate": "ڕۆژی خوازراو",
    "booking.dateNote": "تێبینی: کلینیک ڕۆژی هەینی داخراوە",
    "booking.preferredTime": "کاتی خوازراو",
    "booking.additionalNotes": "تێبینی زیاتر (ئارەزوومەندانە)",
    "booking.notesPlaceholder": "هەر داواکاری یان نیگەرانییەکی تایبەت...",
    "booking.back": "گەڕانەوە",
    "booking.bookViaWhatsapp": "نۆرەی پزیشک لە ڕێگای واتساپ",
    "booking.generalCheckup": "پشکنینی گشتی",
    
    // Chatbot
    "chat.title": "یاریدەدەری ددان",
    "chat.placeholder": "پەیامەکەت بنووسە...",
    "chat.quickServices": "چ خزمەتگوزارییەکان هەن؟",
    "chat.quickHours": "کاتی کارکردن؟",
    "chat.quickBooking": "چۆن نۆرەی پزیشک دابنێم؟",
    
    // Gallery
    "gallery.badge": "گەلەریی وێنەکان",
    "gallery.title1": "کارەکانمان",
    "gallery.title2": "ببینە",
    "gallery.description": "کلینیکی مۆدێرنەکەمان و ئەنجامەکانی چارەسەرەکانی ددان بگەڕێ.",
    "gallery.filterAll": "هەموو",
    "gallery.filterClinic": "کلینیک",
    "gallery.filterResults": "ئەنجامەکان",
    "gallery.clinicTag": "کلینیک",
    "gallery.resultsTag": "ئەنجامەکان",
    "gallery.clinicInterior": "ژووری چارەسەر",
    "gallery.clinicInteriorDesc": "ژووری چارەسەری مۆدێرن بە نوێترین تەکنەلۆژیای ددان.",
    "gallery.receptionArea": "ناوچەی پێشوازی",
    "gallery.receptionAreaDesc": "شوێنێکی ئارام و پێشوازیکەر بۆ نەخۆشەکانمان.",
    "gallery.implantResult": "چاندنی ددان",
    "gallery.implantResultDesc": "پێش و دوای چاندنی ددان بە ئەنجامی سروشتی.",
    "gallery.dentalEquipment": "ئامێری پێشکەوتوو",
    "gallery.dentalEquipmentDesc": "ئامێری ددانی مۆدێرن بۆ چارەسەری ورد.",
    "gallery.dentalCrowns": "تاجی ددان",
    "gallery.dentalCrownsDesc": "تاجی سیرامیکی کوالیتی بەرز بۆ گەڕاندنەوەی بزەیی تەواو.",
    // New gallery items
    "gallery.frontFilling": "پڕکردنەوەی ددانی پێشەوە",
    "gallery.frontFillingDesc": "چاکسازی جوانکاری بۆ ددانی پێشەوە بە شێوەیەکی سروشتی.",
    "gallery.amalgamReplacement": "گۆڕینی پڕکەری ئەمالگەم",
    "gallery.amalgamReplacementDesc": "پڕکەری مۆدێرن جێگرەوەی ئەمالگەمی کۆن بە شێوەیەکی سروشتی.",
    "gallery.smileMakeover": "جوانکاری تەواوی بزەی",
    "gallery.smileMakeoverDesc": "نوێکردنەوەی تەواوی دەم کە بزەیی خراپ دەگۆڕێتە بزەیی جوان.",
    "gallery.perfectSmile": "ئەنجامی بزەیی تەواو",
    "gallery.perfectSmileDesc": "قەشی ددانی سروشتی کە بزەیێکی هاوئاهەنگ دروست دەکات.",
    "gallery.hollywoodSmile": "بزەیی هۆلیوود",
    "gallery.hollywoodSmileDesc": "بزەیێکی سپی سەرسوڕهێنەر بە قەشی سیرامیکی باش.",
    "gallery.zirconEmax": "تاجی زیرکۆن و ئیماکس",
    "gallery.zirconEmaxDesc": "گەڕاندنەوەی بزەیی سروشتی بە تەکنەلۆژیای زیرکۆن و ئیماکس.",
    "gallery.smileTransformation": "گۆڕانی بزەی",
    "gallery.smileTransformationDesc": "پێش و دوای کاریگەر کە هێزی ددانی جوانکاری پیشان دەدات.",
    "gallery.veneerCase": "کەیسی قەش",
    "gallery.veneerCaseDesc": "باشترکردنی بزەی بە قەشی پۆرسلین.",
    "gallery.fullRestoration": "گەڕاندنەوەی تەواوی دەم",
    "gallery.fullRestorationDesc": "نوێکردنەوەی تەواوی ددان بۆ گۆڕانکارییەکی سەرسوڕهێنەر.",
    "gallery.beforeAfterComparison": "پێش و دوا",
    "gallery.beforeAfterComparisonDesc": "بەراوردی تەنیشت یەکتر کە گۆڕانکارییەکی سەرنجڕاکێش پیشان دەدات.",
    "gallery.filterEducational": "پەروەردەیی",
    "gallery.educationalTag": "پەروەردەیی",
    "footer.location": "شوێن",
    
    // FAQ
    "faq.badge": "پرسیارە باوەکان",
    "faq.title1": "پرسیارە",
    "faq.title2": "باوەکان",
    "faq.description": "وەڵامی پرسیارە باوەکان دەربارەی خزمەتگوزارییەکان و کلینیکەکەمان بدۆزەرەوە.",
    "faq.q1": "کاتی کارکردنتان چەندە؟",
    "faq.a1": "کلینیکەکەمان ڕۆژانە لە کاتژمێر ٣:٠٠ ئێوارە تا ٩:٠٠ ئێوارە کراوەیە، جگە لە ڕۆژی هەینی. پێشنیار دەکەین نۆرەی پزیشک پێشوەخت دابنێیت.",
    "faq.q2": "ئایا نەخۆشانی بێ نۆرە وەردەگرن؟",
    "faq.a2": "کاتێک بکرێت پێشوازی لە نەخۆشانی بێ نۆرە دەکەین، بەڵام زۆر پێشنیار دەکەین نۆرەی پزیشک دابنێیت بۆ کەمکردنەوەی کاتی چاوەڕوانی.",
    "faq.q3": "چ خزمەتگوزارییەکانی ددان پێشکەش دەکەن؟",
    "faq.a3": "کۆمەڵێک خزمەتگوزاری تەواو پێشکەش دەکەین لەوانە سپیکردنەوەی ددان، چاندنی ددان، ددانی جوانکاری، چارەسەری کەناڵی ڕەگ، ڕاستکردنەوەی ددان، تیشکی دەم، پاککردنەوەی ددان، و ددانی منداڵان.",
    "faq.q4": "ئایا کلینیکەکە بە تەکنەلۆژیای مۆدێرن ئامادەیە؟",
    "faq.a4": "بەڵێ! کلینیکەکەمان بە نوێترین ئامێری تیشکی ئێکسی دیجیتاڵ و سیستەمی ستیریلایزکردنی مۆدێرن و نوێترین ئامێری ددان ئامادەیە.",
    "faq.q5": "چۆن نۆرەی پزیشک دابنێم؟",
    "faq.a5": "دەتوانیت نۆرەی پزیشک لە ڕێگای فۆرمی نۆرەی ماڵپەڕەکەمان، واتساپ، یان بە پەیوەندیکردن بە ژمارە 07507816500 یان 07781665000 دابنێیت.",
    "faq.q6": "ئایا چاودێری ددان بۆ منداڵان پێشکەش دەکەن؟",
    "faq.a6": "بەدڵنیایی! دکتۆر سەلیم چارەسەری ددانی نەرم و بەخەمی بۆ منداڵانی هەموو تەمەنێک پێشکەش دەکات.",

    // Welcome Screen
    "welcome.title": "بەخێربێن بۆ کلینیکەکەمان",
    "welcome.subtitle": "بزەکەت ئارەزووی ئێمەیە",
    "welcome.skip": "بازدان",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // The address decides the language (/ar, /ku), so search engines can index each one.
    const fromPath = languageFromPath(window.location.pathname);
    if (fromPath && fromPath !== "en") return fromPath;
    try {
      const saved = localStorage.getItem("language") as Language | null;
      if (fromPath === "en" && saved && saved !== "en") return saved;
    } catch {
      // storage unavailable
    }
    return "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem("language", lang);
    } catch {
      // storage unavailable
    }
  };

  // {years} = years since graduating in 2007; it updates itself every year.
  const yearsOfExperience = new Date().getFullYear() - GRADUATION_YEAR;
  const t = (key: string): string => {
    const text = translations[language][key] || translations.en[key] || key;
    if (!text.includes("{years}")) return text;
    const n = language === "en" ? String(yearsOfExperience) : yearsOfExperience.toLocaleString("ar-EG");
    return text.replace("{years}", n);
  };

  const dir = language === "en" ? "ltr" : "rtl";

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
    // On the site's pages, keep the address and search info matched to the shown language.
    const parsed = parsePath(window.location.pathname);
    if (parsed) {
      const target = pathFor(language, parsed.page);
      if (window.location.pathname !== target) {
        window.history.replaceState(window.history.state, "", target + window.location.search + window.location.hash);
      }
      applySeo(language, parsed.page);
    }
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};